language: node_js
node_js:
- 10
sudo: false
branches:
  except:
  - gh-pages
notifications:
  email: false
cache:
  directories:
  - ~/.npm
install: npm ci

# the generated test site will be deployed to S3:
# https://s3-us-west-2.amazonaws.com/mochajs/mocha-docdash/index.html
deploy:
  region: us-west-2
  provider: s3
  bucket: mochajs
  skip_cleanup: true
  local_dir: fixtures-doc
  upload-dir: mocha-docdash
  secret_access_key:
    secure: Zume6QKdjhmgeEjQ9oN3RztxcG7EdxD5VS5z5MBcVxmOmNvD4mF0Pk7PP+j3C/QYRTNU0WMTf6oRWn9kA+bOdYy+5Z5X5B5Vew1hnvkWa5o8G4M7eEsmpEY+1dQsxsfudMTOqGwd4sN+U2ZZapPCp8cOfK/yjety35pQZrkQxx3vpN4/m32D3ofwSWVVA3Fpnpkk54h46FtStPnWHb7XcGzNt2VLGkGGegoJKKB7Z+WZDbQ4D5PJYSbA561mZ7qXBWaQyK2A0vcZ810V7Y0gMohp4JuSlK4FQ1GobJ9z7ZtAkakdGPRArc4SYVHUBuPpWCisOUJ22KZ0Snld1XV09Pitx/myg9qPJ6WjkTLnZv/hThN5hSk8zcdLasZ7HLNXwwDv64prozXErWZYq89q9uBZGuZBVMuGAhZIA5MchN/YHZn+nGKb5t1iGlRS2jbi+qiogEnCLjbn3R42nVHlNmOR30mye9SAzRCspz9slBd9FR+/VyGid3mTY1R3rk/S0TJCmf+smS26Y0tYsDrZ4fjVpqDGCGGfQz288p9GSz28VsyyxLkb33VRGCPX1lqUSeF/s1b5hLvsM+bRY1Kd7H3ZRoXTPVpUzHaUkj5vMHDTeCAKlEdGriIVDzNh8nEtSwJTKe6KIUQ+o8JXUL+t4PZv4XqqIV4bxsiVbcp/+K8=
  access_key_id:
    secure: SLG0xX/khVHiKqlCrMXjHcabRplcuPoOmw6E8sd8ljo0vFIQP7l2nqiKseUH8yizRj42j+bls1hbYbG21Ixon8qEMo8vI95zqQuJAUJbUPEghdgBNLwDRJqh2rzf9zVq2dgmIgDfOUdcw2qV2SFp9CoGGjgVJaKFIwNzmHkJjfx3JJ57paZjINo2xNk/gIvpEz5wYmLUwKZbG7ZCYGHnjlcHaoLle/NSJXQd+Q3NqnK2+R59wYOyoWkfjRIEH4evk4LTtRA+y3tzuDvc+q0HgtvIj+JrtkZbFgIXcTn0DJfF0ZbVV/Zl6/EVjV9IKYVWy+7dtNBcuLz+k1PfR6TvPPEjHvkFcjCxfdHt8wjQJgiIPUEAkbBgfqpMThnf3wX90QK3Fm/21Al6AZM20dYDvBWf9l21jDrlcpuDa0HGg+M96HfZSej2jaq+LXfssb+ttqO3L+mV7jdnMF1RY4R3bS9JfgQsuT7wrfdeE04kzDmJDJNHu7zZrfqawjdopy+SrxE3JYYsFHgmOWdJiDzpYnISoDFJ+iEV8r883Xd2emx+8VElczhAmDpnUZWxMs5i+L40AmwK+MhRyjZq/X1WeMr538kcJUqzXawwLUuoovUB3tPhq65HWEEEcYUrjfQ4QXK3qd0x3Tww8tag1UFY4ERxdOBP/6wS2JZKpB+8oRw=
